import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/header";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Appointment Booking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
